#!/usr/bin/env bash
#
# generate-nigeria-boundaries.sh - Convert per-tenant Nigeria boundary GeoJSON to PMTiles
#
# Requires: tippecanoe (brew install tippecanoe on macOS, or Docker fallback)
#
# Input:  boundaries/nigeria-{tenant}-boundaries.geojson (generated by split-boundaries.js)
# Output: boundaries/nigeria-{tenant}-boundaries.pmtiles (served by Martin)
#
# Usage:
#   ./scripts/generate-nigeria-boundaries.sh                  # All Nigeria tenants
#   ./scripts/generate-nigeria-boundaries.sh --tenant edo     # Single tenant
#   ./scripts/generate-nigeria-boundaries.sh --force          # Regenerate even if exists
#
set -euo pipefail

TENANT_FILTER=""
FORCE=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --tenant|-t) TENANT_FILTER="$2"; shift 2 ;;
        --force|-f) FORCE=true; shift ;;
        *) echo "Unknown argument: $1"; exit 1 ;;
    esac
done

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BASE_DIR="$(dirname "$SCRIPT_DIR")"
BOUNDARIES_DIR="$BASE_DIR/boundaries"

log_info()    { echo -e "\033[34m[INFO] $(date +%H:%M:%S)\033[0m $1"; }
log_success() { echo -e "\033[32m[SUCCESS] $(date +%H:%M:%S)\033[0m $1"; }
log_error()   { echo -e "\033[31m[ERROR] $(date +%H:%M:%S)\033[0m $1"; }
log_warn()    { echo -e "\033[33m[WARN] $(date +%H:%M:%S)\033[0m $1"; }

# Nigeria tenant boundary files
# Format: Name|File
TENANT_DEFS=(
    "edo|nigeria-edo-boundaries"
    "lagos|nigeria-lagos-boundaries"
    "kwara|nigeria-kwara-boundaries"
    "bayelsa|nigeria-bayelsa-boundaries"
    "jigawa|nigeria-jigawa-boundaries"
    "lagos-osun|nigeria-lagos-osun-boundaries"
)

# Filter to single tenant if specified
if [ -n "$TENANT_FILTER" ]; then
    FILTERED=()
    for DEF in "${TENANT_DEFS[@]}"; do
        IFS='|' read -r T_NAME _ <<< "$DEF"
        if [ "$T_NAME" = "$TENANT_FILTER" ]; then
            FILTERED+=("$DEF")
        fi
    done
    if [ ${#FILTERED[@]} -eq 0 ]; then
        log_error "Tenant '$TENANT_FILTER' not found. Available: edo, lagos, kwara, bayelsa, jigawa, lagos-osun"
        exit 1
    fi
    TENANT_DEFS=("${FILTERED[@]}")
fi

# Check if tippecanoe is available natively or via Docker
USE_DOCKER=false
if command -v tippecanoe &>/dev/null; then
    log_info "Using native tippecanoe"
elif command -v docker &>/dev/null; then
    USE_DOCKER=true
    TIPPECANOE_IMAGE="felt-tippecanoe:local"
    DOCKERFILE="$BASE_DIR/scripts/Dockerfile.tippecanoe"

    IMAGE_EXISTS=$(docker images -q "$TIPPECANOE_IMAGE" 2>/dev/null || true)
    if [ -z "$IMAGE_EXISTS" ] || [ "$FORCE" = true ]; then
        log_info "Building tippecanoe (Felt fork) Docker image..."
        docker build -t "$TIPPECANOE_IMAGE" -f "$DOCKERFILE" "$BASE_DIR"
        log_success "Built $TIPPECANOE_IMAGE"
    else
        log_info "Using existing $TIPPECANOE_IMAGE image"
    fi
else
    log_error "Neither tippecanoe nor Docker found."
    log_info "Install tippecanoe: brew install tippecanoe"
    exit 1
fi

echo ""
echo -e "\033[36m================================================================\033[0m"
echo -e "\033[36m  Nigeria Boundary Tile Generator\033[0m"
echo -e "\033[36m  Tenants: ${#TENANT_DEFS[@]}\033[0m"
echo -e "\033[36m================================================================\033[0m"
echo ""

SUCCEEDED=()
FAILED=()
SKIPPED=()

for DEF in "${TENANT_DEFS[@]}"; do
    IFS='|' read -r T_NAME T_FILE <<< "$DEF"
    GEOJSON_FILE="$BOUNDARIES_DIR/${T_FILE}.geojson"
    PMTILES_FILE="$BOUNDARIES_DIR/${T_FILE}.pmtiles"

    # Check source GeoJSON exists
    if [ ! -f "$GEOJSON_FILE" ]; then
        log_error "GeoJSON missing: $GEOJSON_FILE - run 'node scripts/split-boundaries.js' first"
        FAILED+=("$T_NAME: missing GeoJSON")
        continue
    fi

    # Skip if PMTiles already exists (unless --force)
    if [ -f "$PMTILES_FILE" ] && [ "$FORCE" = false ]; then
        SIZE=$(du -m "$PMTILES_FILE" | cut -f1)
        log_info "$T_FILE already exists (${SIZE} MB) - skipping (use --force to regenerate)"
        SKIPPED+=("$T_NAME: exists")
        continue
    fi

    log_info "Generating ${T_FILE}.pmtiles ..."

    TIPPECANOE_ARGS=(
        --output="$PMTILES_FILE"
        --force
        --maximum-zoom=14
        --minimum-zoom=0
        --no-feature-limit
        --no-tile-size-limit
        --detect-shared-borders
        --no-simplification-of-shared-nodes
        --coalesce-densest-as-needed
        --extend-zooms-if-still-dropping
        --layer=boundaries
        --name="$T_FILE"
        --description="Admin boundaries for $T_NAME, Nigeria (states + LGAs)"
    )

    if [ "$USE_DOCKER" = true ]; then
        CONTAINER_NAME="tippecanoe-${T_NAME}-$$"

        docker run --rm \
            -v "${BOUNDARIES_DIR}:/data" \
            "$TIPPECANOE_IMAGE" \
            tippecanoe \
                --output="/data/${T_FILE}.pmtiles" \
                --force \
                --maximum-zoom=14 \
                --minimum-zoom=0 \
                --no-feature-limit \
                --no-tile-size-limit \
                --detect-shared-borders \
                --no-simplification-of-shared-nodes \
                --coalesce-densest-as-needed \
                --extend-zooms-if-still-dropping \
                --layer=boundaries \
                --name="$T_FILE" \
                --description="Admin boundaries for $T_NAME, Nigeria (states + LGAs)" \
                "/data/${T_FILE}.geojson"
        TIPPECANOE_EXIT=$?
    else
        tippecanoe "${TIPPECANOE_ARGS[@]}" "$GEOJSON_FILE"
        TIPPECANOE_EXIT=$?
    fi

    if [ $TIPPECANOE_EXIT -ne 0 ]; then
        log_error "tippecanoe failed for $T_NAME"
        FAILED+=("$T_NAME: tippecanoe error")
        continue
    fi

    if [ -f "$PMTILES_FILE" ] && [ -s "$PMTILES_FILE" ]; then
        SIZE=$(du -m "$PMTILES_FILE" | cut -f1)
        log_success "${T_FILE}.pmtiles generated (${SIZE} MB)"
        SUCCEEDED+=("$T_NAME")
    else
        log_error "No output for $T_NAME"
        FAILED+=("$T_NAME: empty output")
    fi
done

# Summary
echo ""
echo -e "\033[32m================================================================\033[0m"
echo -e "\033[32m  Boundary Generation Complete!\033[0m"
echo -e "\033[32m================================================================\033[0m"

if [ ${#SUCCEEDED[@]} -gt 0 ]; then
    echo ""
    echo -e "  \033[32mGenerated (${#SUCCEEDED[@]}):\033[0m"
    for s in "${SUCCEEDED[@]}"; do
        echo -e "    \033[32m+ $s\033[0m"
    done
fi

if [ ${#SKIPPED[@]} -gt 0 ]; then
    echo ""
    echo -e "  \033[33mSkipped (${#SKIPPED[@]}):\033[0m"
    for s in "${SKIPPED[@]}"; do
        echo -e "    \033[33m~ $s\033[0m"
    done
fi

if [ ${#FAILED[@]} -gt 0 ]; then
    echo ""
    echo -e "  \033[31mFailed (${#FAILED[@]}):\033[0m"
    for f in "${FAILED[@]}"; do
        echo -e "    \033[31m- $f\033[0m"
    done
    echo ""
    log_info "After fixing, restart Docker: docker compose -f tileserver/docker-compose.tenant.yml restart"
    exit 1
fi

echo ""
log_info "Restart Martin to pick up new boundary tiles:"
log_info "  docker compose -f tileserver/docker-compose.tenant.yml restart"
log_info "Verify: curl http://localhost:3000/catalog"
