-- serve-hierarchy.lua
-- Streams the pre-built HDX pcode hierarchy JSON for the tenant's country.
-- Generated by: node scripts/build-hdx-hierarchy.js

local prefix = ngx.var.hdx_prefix
local path   = "/data/hdx/" .. prefix .. "-hierarchy.json"

local f = io.open(path, "r")
if not f then
    ngx.status = 404
    ngx.header["Content-Type"] = "application/json"
    ngx.say('{"error":"Hierarchy not built yet. Run: node scripts/build-hdx-hierarchy.js","code":"HIERARCHY_NOT_FOUND","prefix":"' .. prefix .. '"}')
    return
end

ngx.header["Content-Type"]  = "application/json"
ngx.header["Cache-Control"] = "public, max-age=86400"

local chunk_size = 65536
while true do
    local chunk = f:read(chunk_size)
    if not chunk then break end
    ngx.print(chunk)
end

f:close()
