#
# generate-nigeria-boundaries.ps1 - Convert per-tenant Nigeria boundary GeoJSON to PMTiles
#
# Requires: Docker (uses ghcr.io/felt/tippecanoe)
#
# Input:  boundaries/nigeria-{tenant}-boundaries.geojson (generated by split-boundaries.js)
# Output: boundaries/nigeria-{tenant}-boundaries.pmtiles (served by Martin)
#
# Usage:
#   .\scripts\generate-nigeria-boundaries.ps1              # All Nigeria tenants
#   .\scripts\generate-nigeria-boundaries.ps1 -Tenant edo  # Single tenant
#   .\scripts\generate-nigeria-boundaries.ps1 -Force       # Regenerate even if exists
#

param(
    [string]$Tenant = "",
    [switch]$Force
)

$ErrorActionPreference = "Stop"

$BaseDir = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path))
$BoundariesDir = Join-Path $BaseDir "boundaries"

function Log-Info    { param($msg) Write-Host "[INFO] $(Get-Date -Format 'HH:mm:ss') $msg" -ForegroundColor Blue }
function Log-Success { param($msg) Write-Host "[SUCCESS] $(Get-Date -Format 'HH:mm:ss') $msg" -ForegroundColor Green }
function Log-Error   { param($msg) Write-Host "[ERROR] $(Get-Date -Format 'HH:mm:ss') $msg" -ForegroundColor Red }
function Log-Warn    { param($msg) Write-Host "[WARN] $(Get-Date -Format 'HH:mm:ss') $msg" -ForegroundColor Yellow }

# Nigeria tenant boundary files (must match split-boundaries.js output and Nginx $boundary_source map)
$Tenants = @(
    @{ Name = "edo";        File = "nigeria-edo-boundaries" }
    @{ Name = "lagos";      File = "nigeria-lagos-boundaries" }
    @{ Name = "kwara";      File = "nigeria-kwara-boundaries" }
    @{ Name = "bayelsa";    File = "nigeria-bayelsa-boundaries" }
    @{ Name = "jigawa";     File = "nigeria-jigawa-boundaries" }
    @{ Name = "lagos-osun"; File = "nigeria-lagos-osun-boundaries" }
)

# Filter to single tenant if specified
if ($Tenant -ne "") {
    $Tenants = $Tenants | Where-Object { $_.Name -eq $Tenant }
    if ($Tenants.Count -eq 0) {
        Log-Error "Tenant '$Tenant' not found. Available: edo, lagos, kwara, bayelsa, jigawa, lagos-osun"
        exit 1
    }
}

# Check Docker is available
$hasDocker = $null -ne (Get-Command docker -ErrorAction SilentlyContinue)
if (-not $hasDocker) {
    Log-Error "Docker is required (tippecanoe is not available natively on Windows)"
    Log-Info "Install Docker Desktop: https://www.docker.com/products/docker-desktop/"
    exit 1
}

$TippecanoeImage = "felt-tippecanoe:local"
$Dockerfile = Join-Path $BaseDir "scripts\Dockerfile.tippecanoe"

# Build Felt tippecanoe image locally (v2.x supports PMTiles output)
$imageExists = docker images -q $TippecanoeImage 2>$null
if (-not $imageExists -or $Force) {
    Log-Info "Building tippecanoe (Felt fork) Docker image..."
    docker build -t $TippecanoeImage -f $Dockerfile $BaseDir
    if ($LASTEXITCODE -ne 0) {
        Log-Error "Failed to build tippecanoe image"
        exit 1
    }
    Log-Success "Built $TippecanoeImage"
} else {
    Log-Info "Using existing $TippecanoeImage image"
}

Write-Host ""
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host "  Nigeria Boundary Tile Generator" -ForegroundColor Cyan
Write-Host "  Tenants: $($Tenants.Count)" -ForegroundColor Cyan
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host ""

$succeeded = @()
$failed = @()
$skipped = @()

foreach ($t in $Tenants) {
    $geojsonFile = Join-Path $BoundariesDir "$($t.File).geojson"
    $pmtilesFile = Join-Path $BoundariesDir "$($t.File).pmtiles"

    # Check source GeoJSON exists
    if (-not (Test-Path $geojsonFile)) {
        Log-Error "GeoJSON missing: $geojsonFile - run 'node scripts/split-boundaries.js' first"
        $failed += "$($t.Name): missing GeoJSON"
        continue
    }

    # Skip if PMTiles already exists (unless -Force)
    if ((Test-Path $pmtilesFile) -and -not $Force) {
        $sz = (Get-Item $pmtilesFile).Length / 1MB
        Log-Info ("{0} already exists ({1:N1} MB) - skipping (use -Force to regenerate)" -f $t.File, $sz)
        $skipped += "$($t.Name): exists"
        continue
    }

    Log-Info "Generating $($t.File).pmtiles ..."

    # Use docker cp for output to avoid Windows bind mount write issues.
    # Input is mounted read-only; output goes to /tmp inside container.
    $ContainerName = "tippecanoe-$($t.Name)-$(Get-Random)"

    docker create --name $ContainerName `
        --entrypoint="" `
        -v "${BoundariesDir}:/data:ro" `
        $TippecanoeImage `
        tippecanoe `
            --output="/tmp/$($t.File).pmtiles" `
            --force `
            --maximum-zoom=14 `
            --minimum-zoom=0 `
            --no-feature-limit `
            --no-tile-size-limit `
            --detect-shared-borders `
            --no-simplification-of-shared-nodes `
            --coalesce-densest-as-needed `
            --extend-zooms-if-still-dropping `
            --layer=boundaries `
            --name="$($t.File)" `
            --description="Admin boundaries for $($t.Name), Nigeria (states + LGAs)" `
            "/data/$($t.File).geojson" | Out-Null

    docker start -a $ContainerName
    $tippecanoeExit = $LASTEXITCODE

    if ($tippecanoeExit -ne 0) {
        Log-Error "tippecanoe failed for $($t.Name)"
        $failed += "$($t.Name): tippecanoe error"
        docker rm $ContainerName 2>$null | Out-Null
        continue
    }

    # Copy output from container to host
    docker cp "${ContainerName}:/tmp/$($t.File).pmtiles" $pmtilesFile
    docker rm $ContainerName 2>$null | Out-Null

    if ($LASTEXITCODE -ne 0) {
        Log-Error "Failed to copy output for $($t.Name)"
        $failed += "$($t.Name): docker cp error"
        continue
    }

    if ((Test-Path $pmtilesFile) -and ((Get-Item $pmtilesFile).Length -gt 0)) {
        $sz = (Get-Item $pmtilesFile).Length / 1MB
        Log-Success ("{0}.pmtiles generated ({1:N1} MB)" -f $t.File, $sz)
        $succeeded += "$($t.Name)"
    } else {
        Log-Error "No output for $($t.Name)"
        $failed += "$($t.Name): empty output"
    }
}

# Summary
Write-Host ""
Write-Host "================================================================" -ForegroundColor Green
Write-Host "  Boundary Generation Complete!" -ForegroundColor Green
Write-Host "================================================================" -ForegroundColor Green

if ($succeeded.Count -gt 0) {
    Write-Host ""
    Write-Host "  Generated ($($succeeded.Count)):" -ForegroundColor Green
    foreach ($s in $succeeded) { Write-Host "    + $s" -ForegroundColor Green }
}

if ($skipped.Count -gt 0) {
    Write-Host ""
    Write-Host "  Skipped ($($skipped.Count)):" -ForegroundColor Yellow
    foreach ($s in $skipped) { Write-Host "    ~ $s" -ForegroundColor Yellow }
}

if ($failed.Count -gt 0) {
    Write-Host ""
    Write-Host "  Failed ($($failed.Count)):" -ForegroundColor Red
    foreach ($f in $failed) { Write-Host "    - $f" -ForegroundColor Red }
    Write-Host ""
    Log-Info "After fixing, restart Docker: docker compose -f tileserver/docker-compose.tenant.yml restart"
    exit 1
}

Write-Host ""
Log-Info "Restart Martin to pick up new boundary tiles:"
Log-Info "  docker compose -f tileserver/docker-compose.tenant.yml restart"
Log-Info "Verify: curl.exe http://localhost:3000/catalog"
